### ISSUE TITLE
Voxel size not found in `bs prepare`

### ISSUE THREAD

**Issue by Mohinta2892** [ucsdmanorlab/bootstrapper#2]
Hi!

I am wondering if we can have more concrete example on how to use `bs prepare`, that would be awesome.
As an example below, I am trying to run `bs prepare` on a 3D CREMI cube downloaded from their website, and wrapped in a zarr.

```

bs prepare
Enter path to base directory [path/bootstrapper] >>>  /path/cremi/3d
Existing rounds: ['round1_cremi']

Enter name for round 1 [round_1] >>>  round1_cremi
Enter number of volumes to prepare in /path/cremi/3d/round1_cremi [1] >>>  2

Processing volume 1
Enter name of volume 1 in /path/cremi/3d/round1_cremi [volume_1] >>>  sample_A_20160501     
Enter path to input RAW 3D image, directory of 2D images, or zarr array for sample_A_20160501 >>>  /path/cremi/3d/sample_A_20160501.zarr/volumes/raw
Processing /path/cremi/3d/sample_A_20160501.zarr/volumes/raw
Perform bounding box crop? [y/N] >>>  N
Copy /path/cremi/3d/sample_A_20160501.zarr/volumes/raw to output container /path/cremi/3d/round1_cremi/sample_A_20160501.zarr? [y/N] >>>  y
Enter output RAW dataset path /path/cremi/3d/round1_cremi/sample_A_20160501.zarr/raw] >>>  /path/cremi/3d/round1_cremi/sample_A_20160501.zarr/raw
'voxel_size', try again.
Enter path to input RAW 3D image, directory of 2D images, or zarr array for sample_A_20160501 >>>

```

Input data contains `voxel_size` but it set as `resolution`.

Could you please tell me what I am doing wrong?

Best,
Samia

**Comment by yajivunev** [comment]
The 'resolution' attribute just needs to be renamed to 'voxel_size'. 

See https://github.com/ucsdmanorlab/bootstrapper/blob/main/examples/cremi/download.py

**Comment by yajivunev** [comment]
@Mohinta2892 , Just added a quick fix for preparing zarrs with the 'resolution' attribute @ 47c068f0ac8d0c6e0160b2eebd4dfeb9adcbfe21 -- let me know if this works / makes preparing easier !

**Comment by Mohinta2892** [comment]
Thank you! I was hoping this could be handled by `prepare`.
